---
- name: Download Leap image
  get_url: "{{ image_url }}"
  dest: "{{ images_dir }}"
  checksum: "{{ image_checksum }}"

- name: Modify cloud-init data sources
  become: yes
  shell: |
    - echo "datasource_list: [  Ec2, ConfigDrive, OpenStack, None ]" > 91-dib-cloud-init-datasources.cfg
    - |
    echo "#cloud-config
    datasource:
      Ec2:
        strict_id: false
    " > 92-ec2-datasource.cfg
    - virt-copy-in -a "{{ image_name }}" ./91-dib-cloud-init-datasources.cfg /etc/cloud/cloud.cfg.d
    - virt-copy-in -a "{{ image_name }}" ./92-ec2-datasource.cfg /etc/cloud/cloud.cfg.d
  args:
    chdir: "{{ images_dir }}"
