---
- name: Download OS image
  become: yes
  get_url:
    url: "{{ image_url }}"
    dest: "{{ images_dir }}"
    checksum: "{{ image_checksum }}"

- name: Modify cloud-init config
  become: yes
  shell: |
    virt-edit -a "{{ image_name }}" /etc/cloud/cloud.cfg -e "s/^datasource_list.*/datasource_list: [ ConfigDrive, OpenStack, None ]/"
    virt-edit -a "{{ image_name }}" /etc/cloud/cloud.cfg -e "s/^(\s*)lock_passwd.*/\1lock_passwd: False/"
    md5sum "{{ image_name }}" > "{{ image_name }}".md5
  args:
    chdir: "{{ images_dir }}"
